name: Use Secrets

on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade use-secrets activity
        id: check-secrets
        uses: actions/checkout@v2
        with:
          secrets-context: ${{ toJSON(secrets.YOUR_SECRET) }}
        env: 
          secrets-context: ${{ secrets.YOUR_SECRET }}
       